# Generated by Django 4.2.1 on 2023-05-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_customer_email_remove_customer_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='ProjectTeamMember',
        ),
    ]
